services:
  psql:
    container_name: esus_psql
    restart: always
    image: postgres:13.5
    volumes:
      - ./data/psql_db:/var/lib/postgresql/data
      - ./data/backups:/home
      - ./psql-entrypoint:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRESQL_PORT}:5432"
  pec:
    container_name: esus_app
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_DATABASE=${POSTGRES_DB}
        - POSTGRES_USERNAME=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - TIMEZONE=${TIMEZONE}
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ./install.sh:/var/www/html/install.sh
      - ./run.sh:/var/www/html/run.sh
      - ./data/e-SUS:/opt/e-SUS
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./certificates:/certificates
    ports:
      - "${APP_PORT}:8080"
      - "80:80"
      - "443:443"
    depends_on:
      - psql