services:
  pec:
    container_name: pec
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./esus-data:/opt/e-SUS
      - ./esus-backups:/backups
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
        - DUMPFILE=${DUMPFILE}
        - HTTPS_DOMAIN=${HTTPS_DOMAIN}
    stdin_open: true
    tty: true
    ports:
      - "80:80"
      - "443:443"
