services:
  pec:
    container_name: pec
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env.external-db
    volumes:
      - ./opt-esus:/opt/e-SUS
    build:
      context: .
      dockerfile: Dockerfile.external-db
      args:
        - TZ=${TZ}
        - DB_USER=${POSTGRES_USER}
        - DB_PASS=${POSTGRES_PASSWORD}
        - DUMPFILE=${DUMPFILE}
        - HTTPS_DOMAIN=${HTTPS_DOMAIN}
    stdin_open: true
    tty: true
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"