services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data
  pec:
    container_name: pec
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ./data/e-SUS:/opt/e-SUS
    ports:
      - "${APP_PORT}:8080"
      - "80:80"
      - "443:443"
