services:
  pec:
    container_name: pec
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env.external-db
    build:
      context: .
      dockerfile: Dockerfile.external-db
      args:
        - TIMEZONE=${TIMEZONE}
        - DB_USER=${POSTGRES_USER}
        - DB_PASS=${POSTGRES_PASSWORD}
        - DUMPFILE=${DUMPFILE}
    stdin_open: true
    tty: true
    volumes:
      - ./data/pec:/opt/e-SUS
      - ./nginx/certs:/etc/letsencrypt/live
    ports:
      - "${APP_PORT}:8080"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/letsencrypt/live
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - pec

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt/live
      - ./nginx/challenge:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot -n; sleep 12h & wait $${!}; done;'"