version: "3.8"

services:
  db:
    image: postgres:9.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-esus}
    volumes:
      - esus_db:/var/lib/postgresql/data

  pec:
    build:
      context: .
      dockerfile: Dockerfile.coolify
      args:
        FILENAME: ${FILENAME}
        JAR_FILENAME: ${JAR_FILENAME}
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASS: ${POSTGRES_PASS:-pass}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGRES_DB:-esus}
      TZ: ${TZ:-America/Sao_Paulo}
      TRAINING: ${TRAINING}
    volumes:
      - esus_opt:/opt/e-SUS
      - esus_backups:/backups
    expose:
      - "8080"

volumes:
  esus_opt:
  esus_backups:
  esus_db:


